name: Extract ZIP File

on:
  push:
    paths:
      - '**/*.zip'

jobs:
  extract:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Ensure Unzip is Installed
        run: sudo apt-get install unzip

      - name: Find and Unzip Files
        run: |
          mkdir -p extracted_files
          for file in $(find . -name "*.zip" -type f); do
            unzip "$file" -d extracted_files
          done

      - name: Commit Extracted Files
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add extracted_files
          git commit -m "Extracted ZIP files from workflow"
          git push
